name: GitHub Trophy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: sabari7813
          output_path: assets/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
